---
- hosts: frontend-1
  become: true
  tasks:
    - name: Install Web Server
      yum:
        name: httpd
        state: present
    - name: Start Web Server
      service:
        name: httpd
        state: started
...
