---
- hosts: all
  become: true
  tasks:
    - name: Remove Packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - nano
        - wget
        - httpd
    - name: Remove files
      file:
        dest: /var/www
        state: absent
...
